apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: movie-info-api-authorization
spec:
  selector:
    matchLabels:
      app: movie-info-api
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals:
              {{- range.Values.authorizationPrincipals }}
              - {{ . }}
              {{- end }}
      when:
        - key: request.auth.claims[scope]
          values: ['read:movies']
