apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: movie-api-vs
spec:
  hosts:
    - '*'
  gateways:
    - ingress-gateway
  http:
    - match:
        - uri:
            prefix: '/movie'
      fault:
        delay:
          fixedDelay: 2s
          percentage:
            value: 50
      route:
        - destination:
            host: movie-info-api-svc
