name: Update Develop CI

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and test node app
        uses: ./.github/actions/build-node
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build and push docker image
        uses: ./.github/actions/build-and-push-docker
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}
          image: iagolima96/movie-info:develop

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set Kubernetes context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_KUBECONFIG }}
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Deploy the helm chart
        run: |
          helm upgrade movie-info-api \
          helm \
          --install \


